import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Wedding Invitations', imageId: 'category-wedding' },
  { id: 'cat2', name: 'Birthday Invitations', imageId: 'category-birthday' },
  { id: 'cat3', name: 'Corporate Events', imageId: 'category-corporate' },
  { id: 'cat4', name: 'Party Invitations', imageId: 'category-party' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    slug: 'classic-wedding-invitation',
    name: 'Classic Wedding',
    description: 'A timeless and elegant wedding invitation with beautiful calligraphy.',
    price: 5.99,
    images: ['product-wedding-1', 'product-wedding-2'],
    category: 'Wedding Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod2',
    slug: 'modern-birthday-bash',
    name: 'Modern Birthday Bash',
    description: 'A fun and vibrant birthday invitation perfect for any age.',
    price: 4.50,
    images: ['product-birthday-1', 'product-birthday-2'],
    category: 'Birthday Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod3',
    slug: 'corporate-gala-invite',
    name: 'Corporate Gala Invite',
    description: 'A professional and sophisticated invitation for your next corporate event.',
    price: 7.00,
    images: ['product-corporate-1', 'product-corporate-2'],
    category: 'Corporate Events',
    createdAt: new Date(),
  },
  {
    id: 'prod4',
    slug: 'summer-pool-party',
    name: 'Summer Pool Party',
    description: 'A playful and colorful invitation for a summer pool party.',
    price: 3.99,
    images: ['product-party-1', 'product-party-2'],
    category: 'Party Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod5',
    slug: 'floral-bridal-shower',
    name: 'Floral Bridal Shower',
    description: 'A beautiful and delicate invitation for a bridal shower, featuring floral designs.',
    price: 5.50,
    images: ['product-bridal-1', 'product-bridal-2'],
    category: 'Wedding Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod6',
    slug: 'kids-dinosaur-party',
    name: 'Kids Dinosaur Party',
    description: 'A roaring fun invitation for a child\'s dinosaur-themed birthday party.',
    price: 4.25,
    images: ['product-dino-1', 'product-dino-2'],
    category: 'Birthday Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod7',
    slug: 'elegant-anniversary-invite',
    name: 'Elegant Anniversary',
    description: 'Celebrate a milestone with this elegant anniversary invitation.',
    price: 6.50,
    images: ['product-anniversary-1', 'product-anniversary-2'],
    category: 'Party Invitations',
    createdAt: new Date(),
  },
  {
    id: 'prod8',
    slug: 'business-conference-pass',
    name: 'Business Conference',
    description: 'A clean and modern design for a business conference or seminar.',
    price: 8.00,
    images: ['product-conference-1', 'product-conference-2'],
    category: 'Corporate Events',
    createdAt: new Date(),
  },
  {
    id: 'prod9',
    slug: 'shop-visiting-card',
    name: 'Shop Visiting Card',
    description: 'A professional and eye-catching visiting card for your shop. Designed in a modern, attractive style.',
    price: 10.00,
    images: ['product-visiting-card-1', 'product-visiting-card-2'],
    category: 'Corporate Events',
    createdAt: new Date(),
  },
  {
    id: 'prod10',
    slug: 'rustic-wedding-suite',
    name: 'Rustic Wedding Suite',
    description: 'A charming rustic-themed wedding invitation perfect for a countryside wedding.',
    price: 6.25,
    images: ['product-rustic-wedding-1', 'product-rustic-wedding-2'],
    category: 'Wedding Invitations',
    createdAt: new Date(),
  }
];
