
import type { Product, Category, EditRequest, Order, DealProduct, AppUser, AppRating } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Wedding', imageId: 'category-wedding' },
  { id: 'cat2', name: 'Birthday', imageId: 'category-birthday' },
  { id: 'cat5', name: 'Engagement', imageId: 'category-engagement' },
  { id: 'cat6', name: 'Anniversary', imageId: 'category-anniversary' },
  { id: 'cat7', name: 'Housewarming', imageId: 'category-housewarming' },
  { id: 'cat8', name: 'Baby Shower', imageId: 'category-baby-shower' },
  { id: 'cat9', name: 'Graduation', imageId: 'category-graduation' },
  { id: 'cat3', name: 'Corporate', imageId: 'category-corporate' },
  { id: 'cat4', name: 'Party', imageId: 'category-party' },
  { id: 'cat10', name: 'E-Invite', imageId: 'category-e-invite' },
  { id: 'cat11', name: 'Save the Date', imageId: 'category-save-the-date' },
  { id: 'cat15', name: 'Poster Presentation', imageId: 'category-poster' },
  { id: 'cat16', name: 'Wedding Invitation Video', imageId: 'category-video' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    slug: 'classic-wedding-invitation',
    name: 'Classic Wedding',
    description: 'A timeless and elegant wedding invitation with beautiful calligraphy.',
    price: 5.99,
    images: ['product-wedding-1', 'product-wedding-2'],
    category: 'Wedding',
    createdAt: new Date(),
    zipFileUrl: 'https://example.com/classic-wedding.zip',
    isPaid: true,
  },
  {
    id: 'prod2',
    slug: 'modern-birthday-bash',
    name: 'Modern Birthday Bash',
    description: 'A fun and vibrant birthday invitation perfect for any age.',
    price: 4.50,
    images: ['product-birthday-1', 'product-birthday-2'],
    category: 'Birthday',
    createdAt: new Date(),
    zipFileUrl: 'https://example.com/modern-birthday.zip',
    isPaid: true,
  },
  {
    id: 'prod3',
    slug: 'corporate-gala-invite',
    name: 'Corporate Gala Invite',
    description: 'A professional and sophisticated invitation for your next corporate event.',
    price: 7.00,
    images: ['product-corporate-1', 'product-corporate-2'],
    category: 'Corporate',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod4',
    slug: 'summer-pool-party',
    name: 'Summer Pool Party',
    description: 'A playful and colorful invitation for a summer pool party.',
    price: 3.99,
    images: ['product-party-1', 'product-party-2'],
    category: 'Party',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod5',
    slug: 'floral-bridal-shower',
    name: 'Floral Bridal Shower',
    description: 'A beautiful and delicate invitation for a bridal shower, featuring floral designs.',
    price: 5.50,
    images: ['product-bridal-1', 'product-bridal-2'],
    category: 'Wedding',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod6',
    slug: 'kids-dinosaur-party',
    name: 'Kids Dinosaur Party',
    description: 'A roaring fun invitation for a child\'s dinosaur-themed birthday party.',
    price: 4.25,
    images: ['product-dino-1', 'product-dino-2'],
    category: 'Birthday',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod7',
    slug: 'elegant-anniversary-invite',
    name: 'Elegant Anniversary',
    description: 'Celebrate a milestone with this elegant anniversary invitation.',
    price: 6.50,
    images: ['product-anniversary-1', 'product-anniversary-2'],
    category: 'Anniversary',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod8',
    slug: 'business-conference-pass',
    name: 'Business Conference',
    description: 'A clean and modern design for a business conference or seminar.',
    price: 8.00,
    images: ['product-conference-1', 'product-conference-2'],
    category: 'Corporate',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod9',
    slug: 'shop-visiting-card',
    name: 'Shop Visiting Card',
    description: 'A professional and eye-catching visiting card for your shop. Designed in a modern, attractive style.',
    price: 10,
    images: ['product-visiting-card-1', 'product-visiting-card-2'],
    category: 'Corporate',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod10',
    slug: 'rustic-wedding-suite',
    name: 'Rustic Wedding Suite',
    description: 'A charming rustic-themed wedding invitation perfect for a countryside wedding.',
    price: 6.25,
    images: ['product-rustic-wedding-1', 'product-rustic-wedding-2'],
    category: 'Wedding',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod11',
    slug: 'golden-jubilee-anniversary',
    name: 'Golden Jubilee',
    description: 'A luxurious invitation to celebrate a 50th wedding anniversary.',
    price: 8.5,
    images: ['product-golden-anniv-1', 'product-golden-anniv-2'],
    category: 'Anniversary',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod12',
    slug: 'sweet-sixteen-party',
    name: 'Sweet Sixteen Party',
    description: 'A glamorous and fun invitation for a 16th birthday celebration.',
    price: 5.0,
    images: ['product-sweet-16-1', 'product-sweet-16-2'],
    category: 'Birthday',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod13',
    slug: 'garden-party-invite',
    name: 'Garden Party',
    description: 'A fresh and floral invitation for an elegant garden party.',
    price: 4.75,
    images: ['product-garden-party-1', 'product-garden-party-2'],
    category: 'Party',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod14',
    slug: 'vintage-engagement-announcement',
    name: 'Vintage Engagement',
    description: 'Announce your engagement with this beautiful vintage-style card.',
    price: 5.25,
    images: ['product-vintage-eng-1', 'product-vintage-eng-2'],
    category: 'Engagement',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod15',
    slug: 'minimalist-housewarming',
    name: 'Minimalist Housewarming',
    description: 'A modern and clean design to invite guests to your new home.',
    price: 4.0,
    images: ['product-housewarming-1', 'product-housewarming-2'],
    category: 'Housewarming',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod16',
    slug: 'watercolor-baby-shower',
    name: 'Watercolor Baby Shower',
    description: 'A soft and gentle watercolor design for a baby shower invitation.',
    price: 5.75,
    images: ['product-baby-shower-1', 'product-baby-shower-2'],
    category: 'Baby Shower',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod17',
    slug: 'phd-graduation-announcement',
    name: 'PhD Graduation',
    description: 'A formal announcement for a doctoral graduation.',
    price: 6.0,
    images: ['product-grad-1', 'product-grad-2'],
    category: 'Graduation',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod18',
    slug: 'digital-save-the-date',
    name: 'Digital Save the Date',
    description: 'A modern and eco-friendly digital save-the-date card.',
    price: 3.5,
    images: ['product-save-date-1', 'product-save-date-2'],
    category: 'Save the Date',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod19',
    slug: 'holiday-party-invitation',
    name: 'Holiday Party Fun',
    description: 'A festive invitation for your annual holiday get-together.',
    price: 4.5,
    images: ['product-holiday-1', 'product-holiday-2'],
    category: 'Party',
    createdAt: new Date(),
    isPaid: true,
  },
  {
    id: 'prod20',
    slug: 'e-invite-product-launch',
    name: 'E-Invite Product Launch',
    description: 'A sleek and modern e-invite for a corporate product launch event.',
    price: 7.5,
    images: ['product-launch-1', 'product-launch-2'],
    category: 'E-Invite',
    createdAt: new Date(),
    isPaid: true,
  },
];

export const editRequests: EditRequest[] = [
  {
    id: 'req1',
    productId: 'prod1',
    productName: 'Classic Wedding',
    requestDetails: 'Please change the main font to "Great Vibes" and the wedding date to October 26, 2024.',
    status: 'Approved',
    requestedAt: new Date('2023-10-01T10:00:00Z'),
    updatedAt: new Date('2023-10-01T18:30:00Z'),
    userId: 'usr1',
    userName: 'John Doe',
    userEmail: 'john.doe@example.com',
    turnaroundTime: '2 Days',
  },
  {
    id: 'req2',
    productId: 'prod2',
    productName: 'Modern Birthday Bash',
    requestDetails: 'Can you change the age from "30th" to "40th" and use a blue color scheme instead of pink?',
    status: 'Pending',
    requestedAt: new Date('2023-10-05T14:15:00Z'),
    updatedAt: new Date('2023-10-05T14:15:00Z'),
    userId: 'usr2',
    userName: 'Jane Smith',
    userEmail: 'jane.smith@example.com',
    turnaroundTime: 'Urgent',
  },
  {
    id: 'req3',
    productId: 'prod3',
    productName: 'Corporate Gala Invite',
    requestDetails: 'Add our company logo to the top right corner. I have emailed it to you.',
    status: 'Pending',
    requestedAt: new Date('2023-10-06T09:00:00Z'),
    updatedAt: new Date('2023-10-06T09:00:00Z'),
    userId: 'usr1',
    userName: 'John Doe',
    userEmail: 'john.doe@example.com',
    turnaroundTime: '1 Day',
  },
  {
    id: 'req4',
    productId: 'prod4',
    productName: 'Summer Pool Party',
    requestDetails: 'This request is not feasible. Please add a unicorn that flies across the card.',
    status: 'Rejected',
    requestedAt: new Date('2023-09-28T11:00:00Z'),
    updatedAt: new Date('2023-09-29T16:45:00Z'),
    userId: 'usr2',
    userName: 'Jane Smith',
    userEmail: 'jane.smith@example.com',
    turnaroundTime: '2 Days',
  },
];


export const orders: Order[] = [
    {
        id: 'ord1',
        items: [
            { productId: 'prod9', productName: 'Shop Visiting Card', quantity: 2, price: 10 },
            { productId: 'prod2', productName: 'Modern Birthday Bash', quantity: 1, price: 4.50 },
        ],
        total: 24.50,
        status: 'Delivered',
        createdAt: new Date('2023-09-15T11:30:00Z'),
    },
    {
        id: 'ord2',
        items: [
            { productId: 'prod7', productName: 'Elegant Anniversary', quantity: 1, price: 6.50 },
        ],
        total: 6.50,
        status: 'Shipped',
        createdAt: new Date('2023-10-02T18:00:00Z'),
    },
    {
        id: 'ord3',
        items: [
            { productId: 'prod1', productName: 'Classic Wedding', quantity: 50, price: 5.99 },
            { productId: 'prod10', productName: 'Rustic Wedding Suite', quantity: 50, price: 6.25 },
        ],
        total: 612.00,
        status: 'Placed',
        createdAt: new Date('2023-10-07T10:00:00Z'),
    },
];

const offerEndDate = new Date();
offerEndDate.setHours(offerEndDate.getHours() + 24);

export const dealProduct: DealProduct = {
  id: 'dealprod1',
  slug: 'shampoo-conditioner-facewash',
  name: 'Shampoo, Conditioner & Facewash',
  description: 'A complete grooming kit for men. The ultimate swagger pack for everyday freshness.',
  price: 200,
  discountPrice: 150,
  images: ['product-deal-1'],
  category: 'Personal Care',
  createdAt: new Date(),
  offerEndsAt: offerEndDate,
  stock: 60,
  sold: 20,
  rating: 3.5,
  zipFileUrl: 'https://example.com/shampoo.zip',
  isPaid: true,
};

const offerEndDate2 = new Date();
offerEndDate2.setDate(offerEndDate2.getDate() + 1);

export const dealProduct2: DealProduct = {
  id: 'dealprod2',
  slug: 'luxury-watch-set',
  name: 'Luxury Watch & Wallet Set',
  description: 'An elegant gift set featuring a classic timepiece and a leather wallet.',
  price: 500,
  discountPrice: 399,
  images: ['product-deal-2'],
  category: 'Gifts',
  createdAt: new Date(),
  offerEndsAt: offerEndDate2,
  stock: 30,
  sold: 8,
  rating: 4.5,
  isPaid: true,
};

const offerEndDate3 = new Date();
offerEndDate3.setDate(offerEndDate3.getDate() + 2);

export const dealProduct3: DealProduct = {
  id: 'dealprod3',
  slug: 'artisan-leather-journal',
  name: 'Artisan Leather Journal',
  description: 'A handcrafted leather journal, perfect for notes, sketches, and thoughts.',
  price: 250,
  discountPrice: 199,
  images: ['product-deal-3'],
  category: 'Stationery',
  createdAt: new Date(),
  offerEndsAt: offerEndDate3,
  stock: 100,
  sold: 45,
  rating: 4.8,
  isPaid: true,
};

export const initialUsers: AppUser[] = [
  { id: 'usr1', name: 'John Doe', email: 'john.doe@example.com', phone: '1234567890', createdAt: new Date('2023-10-01') },
  { id: 'usr2', name: 'Jane Smith', email: 'jane.smith@example.com', phone: '0987654321', createdAt: new Date('2023-09-25') },
  { id: 'usr3', name: 'Admin User', email: 'abhayrat603@gmail.com', phone: '8463062603', createdAt: new Date('2023-09-20') },
];

export const initialAppRatings: AppRating[] = [
  { id: 'rating1', userId: 'usr1', userName: 'John Doe', rating: 5, comment: "This app is amazing! So easy to create beautiful invitations. Highly recommended!", createdAt: new Date('2023-10-05T10:00:00Z') },
  { id: 'rating2', userId: 'usr2', userName: 'Jane Smith', rating: 4, comment: "Great selection of designs. The edit request feature is very useful. Sometimes the app can be a little slow, but overall a great experience.", createdAt: new Date('2023-10-04T15:30:00Z') },
  { id: 'rating3', userId: 'usr3', userName: 'Admin User', rating: 5, comment: "As the admin, I find the panel very intuitive and easy to manage products and users.", createdAt: new Date('2023-10-03T12:00:00Z') },
];
