import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'cat1', name: 'Apparel', imageId: 'category-apparel' },
  { id: 'cat2', name: 'Footwear', imageId: 'category-footwear' },
  { id: 'cat3', name: 'Accessories', imageId: 'category-accessories' },
  { id: 'cat4', name: 'Gear', imageId: 'category-gear' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    slug: 'dynamic-performance-tee',
    name: 'Dynamic Performance Tee',
    description: 'A lightweight and breathable tee designed for high-intensity workouts. Wicks away sweat to keep you dry and comfortable.',
    price: 39.99,
    images: ['product-tee-1', 'product-tee-2'],
    category: 'Apparel',
    createdAt: new Date(),
  },
  {
    id: 'prod2',
    slug: 'velocity-running-shorts',
    name: 'Velocity Running Shorts',
    description: 'Experience ultimate freedom of movement with these lightweight running shorts, featuring a built-in liner and secure pocket.',
    price: 49.99,
    images: ['product-shorts-1', 'product-shorts-2'],
    category: 'Apparel',
    createdAt: new Date(),
  },
  {
    id: 'prod3',
    slug: 'air-stride-sneakers',
    name: 'Air-Stride Sneakers',
    description: 'Cushioned and responsive, these sneakers are perfect for your daily run or a walk in the park. Engineered mesh for breathability.',
    price: 129.99,
    images: ['product-sneakers-1', 'product-sneakers-2'],
    category: 'Footwear',
    createdAt: new Date(),
  },
  {
    id: 'prod4',
    slug: 'motion-tech-hoodie',
    name: 'Motion-Tech Hoodie',
    description: 'A versatile hoodie made from stretchable fabric that moves with you. Ideal for warm-ups, cool-downs, or casual wear.',
    price: 89.99,
    images: ['product-hoodie-1', 'product-hoodie-2'],
    category: 'Apparel',
    createdAt: new Date(),
  },
  {
    id: 'prod5',
    slug: 'all-terrain-backpack',
    name: 'All-Terrain Backpack',
    description: 'Durable and water-resistant, this backpack is ready for any adventure. Multiple compartments for organized storage.',
    price: 79.99,
    images: ['product-backpack-1', 'product-backpack-2'],
    category: 'Accessories',
    createdAt: new Date(),
  },
  {
    id: 'prod6',
    slug: 'hydro-flow-water-bottle',
    name: 'Hydro-Flow Water Bottle',
    description: 'Stay hydrated with this insulated stainless steel water bottle. Keeps your drinks cold for 24 hours or hot for 12.',
    price: 29.99,
    images: ['product-bottle-1'],
    category: 'Gear',
    createdAt: new Date(),
  },
  {
    id: 'prod7',
    slug: 'pro-fit-cap',
    name: 'Pro-Fit Cap',
    description: 'A sleek, comfortable cap with moisture-wicking technology. Perfect for sunny days on the track or trail.',
    price: 24.99,
    images: ['product-cap-1', 'product-cap-2'],
    category: 'Accessories',
    createdAt: new Date(),
  },
  {
    id: 'prod8',
    slug: 'trail-blazer-hiking-boots',
    name: 'Trail-Blazer Hiking Boots',
    description: 'Conquer any trail with these rugged, waterproof hiking boots. Superior grip and ankle support for challenging terrains.',
    price: 159.99,
    images: ['product-boots-1', 'product-boots-2'],
    category: 'Footwear',
    createdAt: new Date(),
  },
];
